### ISSUE TITLE
权值文件

### ISSUE THREAD

**Issue by Alex-Beh** [bubbliiiing/facenet-retinaface-pytorch#1]
你好， 请问能上传权值文件至github吗?我从百度王盘下载不了...... 谢谢

和这文件下的权值文件一样吗? https://github.com/bubbliiiing/facenet-retinaface-pytorch/tree/main/model_data

**Comment by bubbliiiing** [comment]
emm这里面的都是mobilenet的，还有一个比较大一些的，百度网盘下不了是怎么回事

**Comment by Brittanygirl** [comment]
请问有 Resnet50的模型权重嘛

**Comment by bubbliiiing** [comment]
pytorch官方给了
