### ISSUE TITLE
(-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'

### ISSUE THREAD

**Issue by yancccc** [bubbliiiing/facenet-retinaface-pytorch#10]
使用自己的数据集，运行python encoding.py报错。
new_img = cv2.warpAffine(img,RotationMatrix,(img.shape[1],img.shape[0])) 
cv2.error: OpenCV(4.4.0) /home/ycc/opencv-4.4.0/modules/imgproc/src/imgwarp.cpp:2594: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'
请问是什么原因呢？

**Comment by Storm0921** [comment]
我也遇到了同样的问题，你是怎么解决的？
