### ISSUE TITLE
检测延迟

### ISSUE THREAD

**Issue by SSTato** [bubbliiiing/facenet-retinaface-pytorch#6]
我在用这个做摄像头检测的时候发现，retinaface.detect_image函数处理时间太长了，导致摄像头检测有很高的延迟，有什么好的办法解决这个问题吗？

**Comment by SSTato** [comment]
而且我在进行摄像头检测的时候，CPU占用率很高，GPU几乎没用

**Comment by SSTato** [comment]
> fps显示多少呢

二三十，FPS不低

**Comment by SSTato** [comment]
另外检测的精度也不太高，阈值设0.9容易认错人，0.8又都认不出来，大佬教教我怎么弄

**Comment by bubbliiiing** [comment]
二三十，延迟很高吗
mobilenet精度不高，你用renset的facenet或者我提供的arcface库

**Comment by SSTato** [comment]
另外检测的精度也不太高，阈值设0.9容易认错人，0.8又都认不出来，大佬教教我怎么弄

> 二三十，延迟很高吗 mobilenet精度不高，你用renset的facenet或者我提供的arcface库

就是画面显示的是我几秒前的动作，不是卡顿，是延迟

**Comment by SSTato** [comment]
> 二三十，延迟很高吗 mobilenet精度不高，你用renset的facenet或者我提供的arcface库

用senset后只有十左右的FPS，延迟了十多秒，这是什么情况，我用yolov5测试了一下，大概一秒的延迟，CPU利用率也不高，我检查了一下，就用这个torch.from_numpy的时候占了大量cpu

**Comment by SSTato** [comment]
> > 二三十，延迟很高吗 mobilenet精度不高，你用renset的facenet或者我提供的arcface库
> 
> 用senset后只有十左右的FPS，延迟了十多秒，这是什么情况，我用yolov5测试了一下，大概一秒的延迟，CPU利用率也不高，我检查了一下，就用这个torch.from_numpy的时候占了大量cpu

但是CPU占用告和延迟没关系，延迟高是因为那个调用人脸识别的原因，我通过单独运行每行代码发现的，这个要怎么解决呀

**Comment by bubbliiiing** [comment]
你要用更好的人脸识别网络，也就是facenet，而不是更好的人脸检测网络，即不是retinaface。

**Comment by bubbliiiing** [comment]
我听你的描述是检测网络耗时更长。

**Comment by bubbliiiing** [comment]
理论上fps20-30的话应该不会有很高的延迟呀😂，不过opencv的读取就会有缓存在里面我记得，你十多秒的检测有点离谱了

**Comment by SSTato** [comment]
> 你要用更好的人脸识别网络，也就是facenet，而不是更好的人脸检测网络，即不是retinaface。

那现在检测网络耗时长怎么办呢

**Comment by bubbliiiing** [comment]
说实话延迟十多秒感觉可能不是网络检测速度的问题，也许该看看摄像头设置啊什么的，会好一点，以及cv如何读取摄像头

**Comment by SSTato** [comment]
> 说实话延迟十多秒感觉可能不是网络检测速度的问题，也许该看看摄像头设置啊什么的，会好一点，以及cv如何读取摄像头

一开始我也以为是摄像头的原因，但是同样的环境下，我用yolov5就没有延迟的问题，所以我排除了是摄像头的问题

**Comment by SSTato** [comment]
> > 说实话延迟十多秒感觉可能不是网络检测速度的问题，也许该看看摄像头设置啊什么的，会好一点，以及cv如何读取摄像头
> 
> 一开始我也以为是摄像头的原因，但是同样的环境下，我用yolov5就没有延迟的问题，所以我排除了是摄像头的问题

并且，我把检测代码注释掉，就不存在延迟的问题，可以确定是检测产生的延迟

**Comment by SSTato** [comment]
![image](https://user-images.githubusercontent.com/93987794/180695190-feee92d2-8271-4d95-ae0e-3848f1b44fc5.png)
我加了一个取帧操作后，问题得到了解决，没有了延迟，并且cpu占用率也下来了。

**Comment by bubbliiiing** [comment]
好的哥，你可以把代码贴一下吗

**Comment by SSTato** [comment]
> 好的哥，你可以把代码贴一下吗

取帧的话要把检测框和关键点显示那里删掉，就是画面不显示任何东西就是原画面，只返回输出结果，这样才不卡，感觉很鸡肋，就没必要贴了吧。

**Comment by bubbliiiing** [comment]
好吧0 0
